'use strict'

var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var notasNuevasSchema = Schema({
    //hoteleria Hospital
    Cliente: String,
    FechaRecolecta: Date,
    NumeroNota:Number,
    almoada:Number,
    fundasAlmohadasViejas:Number,
    fundasAlmohadasNuevas:Number,
    sabanaNueva:Number,
    sabanaVieja:Number,
    toallaDeBañoVeja:Number,
    toallaDeBañoNueva:Number,
    tapeteDeBañoVieja:Number,
    tapeteDeBañoNueva:Number,
    toallaDeManoVieja:Number,
    toallaDeManoNueva:Number,
    toallaFacial:Number,
    bataDeBaño:Number,
    cobertor:Number,
    edrecolcha:Number,
    relleno:Number,
    cortinaDeBaño:Number,
    rodapie:Number,
    dubeth:Number,
    protectorDeColchon:Number,
    pieDeCama:Number,
    limpion:Number,
    cortinaBlackout:Number,
    //descartes toalla B Hospital
    toallaDeBañoDescartesClorhexidina:Number,
    toallaDeBañoDescartesArrastre:Number,
    toallaDeBañoDescartesTinta:Number,
    toallaDeBañoDescartesVieja:Number,
    toallaDeBañoDescartesCloro:Number,
    toallaDeBañoDescartesPuntoAzul:Number,
    //descartes Cobertor Hospital
    cobertorDescartesClorhexidina:Number,
    cobertorDescartesArrastre:Number,
    cobertorDescartesTinta:Number,
    cobertorDescartesVieja:Number,
    cobertorDescartesCloro:Number,
    cobertorDescartesPuntoAzul:Number,
    //descartes Toalla de mano Hospital
    toallaDeManoDescartesClorhexidina:Number,
    toallaDeManoDescartesArrastre:Number,
    toallaDeManoDescartesTinta:Number,
    toallaDeManoDescartesVieja:Number,
    toallaDeManoDescartesCloro:Number,
    toallaDeManoDescartesPuntoAzul:Number,
    //servicios ExtHospital
    bataAislamiento:Number,
    bataPaciente:Number,
    bataRegular:Number,
    //Manteleria
    moyeton:Number,
    moyetonPlastificado:Number,
    banda:Number,
    camino:Number,
    bambalina:Number,
    bambalinaGrande:Number,
    cubreSilla:Number,
    cubreCharola:Number,
    cubreCabrilla:Number,
    cubreMantel:Number,
    liston:Number,
    tablon:Number,
    tablonGrande:Number,
    mantelGrande:Number,
    mantelMediano:Number,
    mantelRedondo:Number,
    mantelImperial:Number,
    mantelSpandex:Number,
    servilleta:Number,
    cortinaNegra:Number,
    moño:Number,
    bandera:Number,
    //ropa ExtExpo guadalajara
    filipina:Number,
    chamarraTermica:Number,
    chaleco:Number,
    trajeDeBombero5pz:Number,
    //serviciosFrente
    encargoPorKilo:Number,
    planchaDocena:Number,
    planchaPieza:Number,
    blusas:Number,
    camisas:Number,
    corbatas:Number,
    chamarras:Number,
    playeras:Number,
    faldas:Number,
    pantalones:Number,
    sacos:Number,
    sweters:Number,
    trajes2Pz:Number,
    trajes3Pz:Number,
    vestidos:NumeroNota,
    

});

module.exports= mongoose.model('notasNuevas',notasNuevasSchema);
//  notasNuevas --> guarda los documentos en la coleccion 